# Generated by Django 4.2.6 on 2023-10-24 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("color", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "description"],
                        name="name_description_filter_index",
                    )
                ],
            },
        ),
    ]
