# Generated by Django 4.2.6 on 2023-10-25 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotion_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Promotion price based on the product category discount",
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
