# Generated by Django 4.2.6 on 2023-10-25 13:08

from django.apps.registry import Apps
from django.db import migrations, models


def create_initial_categories(apps: Apps, schema_editor) -> None:
    Category: type[models.Model] = apps.get_model("categories", "Category")
    categories: list[Category] = []
    for name, discount in [
        ("Smartphones", 2.55),
        ("Furniture", 3),
        ("Eletronics", 4.3),
        ("Appliances", 5),
        ("Refrigerators", 7.5),
    ]:
        categories.append(Category(name=name, discount=discount))
    Category.objects.bulk_create(categories)


def reset_categories(apps: Apps, schema_editor) -> None:
    Category: type[models.Model] = apps.get_model("categories", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_discount"),
    ]

    operations = [
        migrations.operations.RunPython(create_initial_categories, reset_categories)
    ]
